bad_channels_dict = {
    100:{
        # 'a_closed_eyes':[['F4','FT8','T8'],['FT8','T8'],['FT8','T8'],['FT8','T8'],],
        # 'a_opened_eyes':[['F4','FT8','T8'],['FT8','T8'],['FT8','T8'],['FT8','T8'],],
        'a_closed_eyes':[[],[],[],[]],
        'a_opened_eyes':[[],[],[],[]],
    
        # 'b_closed_eyes':[['FT8',],['FT8',],['FT8',],],
        # 'b_opened_eyes':[['FT8','T8'],['FT8','T8'],['FT8','T8'],],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    101:{
        ## POz, AF4, PO3
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    102:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    103:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    104:{
        ## PO3, P5, FT8, AF4
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    105:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    200:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    201:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    202:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    1:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    2:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    3:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    4:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    5:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    6:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
    7:{
        'a_closed_eyes':[[],[],[]],
        'a_opened_eyes':[[],[],[]],
        'b_closed_eyes':[[],[],[]],
        'b_opened_eyes':[[],[],[]],
    },
}