bad_channels_dict = {
    100:{
        'session_0':{
            # 'general':['T8'],
            'baseline':[['FT8','T8']],
            'a_closed_eyes':[['FT8','T8'],['FT8','T8'],['FT8','T8'],],
            'a_opened_eyes':[['FT8','T8'],['F4','FT8','T8'],['FT8','T8'],],
            'b_closed_eyes':[['FT8','T8'],['FT8','T8'],['FT8','T8'],],
            'b_opened_eyes':[['FT8','T8'],['FT8','T8'],['FT8','T8'],],
        },
    },
    101:{
        'session_0':{
            # 'general':[],
            ## POz, AF4, PO3
            'baseline':[['AF4']],
            'a_closed_eyes':[['AF4'],['AF4'],['AF4']],
            'a_opened_eyes':[['AF4'],['AF4'],['AF4','T7']],
            'b_closed_eyes':[['AF4'],['AF4'],['AF4','T7','T8']],
            'b_opened_eyes':[['AF4'],['AF4'],['AF4']],
        },
    },
    102:{
        'session_0':{
            'general':[],
            'a_closed_eyes':[[],[],[]],
            'a_opened_eyes':[[],[],[]],
            'b_closed_eyes':[[],[],[]],
            'b_opened_eyes':[[],[],[]],
        },
    },
    103:{
        'session_0':{
            'general':[],
            'a_closed_eyes':[[],[],[]],
            'a_opened_eyes':[[],[],[]],
            'b_closed_eyes':[[],[],[]],
            'b_opened_eyes':[[],[],[]],
        },
    },
    104:{
        'session_0':{
            'general':[],
            ## PO3, P5, FT8, AF4
            'a_closed_eyes':[[],[],[]],
            'a_opened_eyes':[[],[],[]],
            'b_closed_eyes':[[],[],[]],
            'b_opened_eyes':[[],[],[]],
        },
    },
    105:{
        'session_0':{
            'general':[],
            'a_closed_eyes':[[],[],[]],
            'a_opened_eyes':[[],[],[]],
            'b_closed_eyes':[[],[],[]],
            'b_opened_eyes':[[],[],[]],
        },
    },
    200:{
        'session_0':{
            'general':[],
            'a_closed_eyes':[[]]*3,
            'a_opened_eyes':[[]]*3,
            'b_closed_eyes':[[]]*3,
            'b_opened_eyes':[[]]*3,
        },
    },
    201:{
        'session_0':{
            'general':[],
            'a_closed_eyes':[[]]*3,
            'a_opened_eyes':[[]]*3,
            'b_closed_eyes':[[]]*3,
            'b_opened_eyes':[[]]*3,
        },
    },
    202:{
        'session_0':{
            'general':[],
            'a_closed_eyes':[[]]*3,
            'a_opened_eyes':[[]]*3,
            'b_closed_eyes':[[]]*3,
            'b_opened_eyes':[[]]*3,
        },
    },
    1:{
        'session_0':{
            # 'general':['E48','E119'],
            'general':[],
            'baseline':[[],[],[],],
            'a_closed_eyes':[[],['E119',],[],],
            'a_opened_eyes':[[],['E119',],['E119',],],

            'b_closed_eyes':[['E45','E119','E127'],['E45','E119','E127'],['E119',],],
            'b_opened_eyes':[['E45','E119',],['E45','E119',],[],],
        },
        'session_1':{
            'general':[],
            'baseline':[[],[],[],],
            'a_closed_eyes':[[]]*3,
            'a_opened_eyes':[[]]*3,
            'b_closed_eyes':[[]]*3,
            'b_opened_eyes':[[]]*3,
        }
    },
    2:{
        'session_0':{
            'general':['E8','E55'],
            'a_closed_eyes':[['E8','E55']]*3,
            'a_opened_eyes':[['E8','E55']]*3,
            'b_closed_eyes':[['E8','E55']]*3,
            'b_opened_eyes':[['E8','E55']]*3,
        },
    },
    3:{
        'session_0':{
            'general':['E45','E49','E56','E57','E62','E72','E78','E79','E85','E86','E92','E95'],
            ## signals degradation increases with time
            'a_closed_eyes':[['E45','E49','E56','E57','E62','E72','E78','E79','E85','E86','E92','E95']]*3,
            'a_opened_eyes':[['E45','E49','E56','E57','E62','E72','E78','E79','E85','E86','E92','E95']]*3,
            'b_closed_eyes':[['E45','E49','E56','E57','E62','E72','E78','E79','E85','E86','E92','E95']]*3,
            'b_opened_eyes':[['E45','E49','E56','E57','E62','E72','E78','E79','E85','E86','E92','E95']]*3,
        },
        'session_1':{
            'general':[],
            'a_closed_eyes':[[]]*3,
            'a_opened_eyes':[[]]*3,
            'b_closed_eyes':[[]]*3,
            'b_opened_eyes':[[]]*3,
        },
    },
    4:{
        'session_0':{
            'general':[],
            'a_closed_eyes':[['E20','E44','E48','E114']]*3,
            'a_opened_eyes':[['E20','E44','E48','E114']]*3,
            'b_closed_eyes':[['E20','E44','E48','E114']]*3,
            'b_opened_eyes':[['E20','E44','E48','E114']]*3,
        },
    },
    5:{
        'session_0':{
            'general':[],
            'a_closed_eyes':[['E20','E43','E44','E113']]*3,
            'a_opened_eyes':[['E20','E43','E44','E113']]*3,
            'b_closed_eyes':[['E20','E43','E44','E113']]*3,
            'b_opened_eyes':[['E20','E43','E44','E113']]*3,
        },

    },
    6:{
        'session_0':{
            'general':['E37','E43','E48'],
            'a_closed_eyes':[['E37','E43','E48']]*3,
            'a_opened_eyes':[['E37','E43','E48']]*3,
            'b_closed_eyes':[['E37','E43','E48']]*3,
            'b_opened_eyes':[['E37','E43','E48']]*3,
        },
        'session_1':{
            'general':[],
            'a_closed_eyes':[[]]*3,
            'a_opened_eyes':[[]]*4,
            'b_closed_eyes':[[]]*3,
            'b_opened_eyes':[[]]*3,
        },
    },
    7:{
        'session_0':{
            'general':[],
            'a_closed_eyes':[['E48']]*3,
            'a_opened_eyes':[['E48']]*3,
            'b_closed_eyes':[['E48']]*3,
            'b_opened_eyes':[['E48']]*3,
        },
        'session_1':{
            'general':[],
            'a_closed_eyes':[[]]*3,
            'a_opened_eyes':[[]]*3,
            'b_closed_eyes':[[]]*3,
            'b_opened_eyes':[[]]*3,
        },
    },
    'ref':{
        'session_0':{
            'general':[],
            'a_closed_eyes':[[]]*3,
            'a_opened_eyes':[[]]*3,
            'b_closed_eyes':[[]]*3,
            'b_opened_eyes':[[]]*3,
        },
    },
}