blinks_components_dict = {
    101:{
        'session_0':{
            'baseline':[[],[],[],],
            'a_closed_eyes':[[],[],[],],
            'a_opened_eyes':[[2],[2],[2],],
            'b_closed_eyes':[[],[],[],],
            'b_opened_eyes':[[],[],[],],
        },
    },
    1:{
        'session_0':{
            'baseline':[[3],[],[],],
            'a_closed_eyes':[[],[],[],],
            'a_opened_eyes':[[3],[4],[3],],
            'b_closed_eyes':[[],[],[],],
            'b_opened_eyes':[[3],[2],[7],],
        },
        'session_1':{
            'a_closed_eyes':[[],[],[],],
            'a_opened_eyes':[[2],[1],[2],],
            'b_closed_eyes':[[],[],[],],
            'b_opened_eyes':[[1],[3],[3],],
        },
    }
}