selected_sequences_dict = {
    100:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':1,
        'b_opened_eyes':1,
    },
    101:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':1,
        'b_opened_eyes':1,
    },
    102:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':1,
        'b_opened_eyes':1,
    },
    103:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':1,
        'b_opened_eyes':1,
    },
    104:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':0,
        'b_opened_eyes':0,
    },
    105:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':1,
        'b_opened_eyes':1,
    },
    200:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':1,
        'b_opened_eyes':1,
    },
    201:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':1,
        'b_opened_eyes':1,
    },
    202:{
        'a_closed_eyes':0,
        'a_opened_eyes':0,
        'b_closed_eyes':0,
        'b_opened_eyes':0,
    },
      1:{
        'a_closed_eyes':0,
        'a_opened_eyes':0,
        'b_closed_eyes':1,
        'b_opened_eyes':1,

      },
      2:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':1,
        'b_opened_eyes':1,
      },
      3:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':1,
        'b_opened_eyes':1,
      },
      4:{
        'a_closed_eyes':2,
        'a_opened_eyes':2,
        'b_closed_eyes':2,
        'b_opened_eyes':2,
      },
      5:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':2,
        'b_opened_eyes':2,
      },
      6:{
          'a_closed_eyes':1,
          'a_opened_eyes':1,
          'b_closed_eyes':1,
          'b_opened_eyes':1,
    },
      7:{
        'a_closed_eyes':1,
        'a_opened_eyes':1,
        'b_closed_eyes':1,
        'b_opened_eyes':1,
      },
}